

name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-dev:
    runs-on: self-hosted
    environment: dev
    container:
      image: alpine
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Secret
        run: echo ${{ secrets.AKO }}
  build-prod:
    runs-on: self-hosted
    environment: prod
    container:
      image: alpine
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Secret
        run: echo ${{ secrets.AKO }}
