

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  


jobs:
  set_vars:
    runs-on: self-hosted
    container:
      image: alpine
    
    steps:
      - name: Test Action
        uses: geoakaki/actions/testaction@v1
        with:
          dotnet-version: 5.0.x
          project-path: src/DemoReusableTemplates.csproj
          
