name: Test Acction

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-stage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install curl
        run: echo test
