name: Test Acction

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-stage:
    runs-on: self-hosted
    #container:
    #  image: alpine
    steps:
      - uses: actions/checkout@v3
      - name: Docker Version
        run: docker version
      - name: Install curl
        run: echo test
