name: PR Branch Info

on:
  pull_request:
    types: [closed]
    branches: ["**"]

jobs:
  print-branch-info:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Print Branch Information
        run: |
          echo "===== PR Merge Information ====="
          echo "Current Branch: ${{ github.ref_name }}"
          echo "Source Branch (Head): ${{ github.event.pull_request.head.ref }}"
          echo "Destination Branch (Base): ${{ github.event.pull_request.base.ref }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "================================"
