name: Test Acction

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-stage:
    runs-on: [self-hosted, databases]
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install curl
        run: apt update && apt install -y curl
