name: Test Actions
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  TVAR1: "test var"
  TVAR2: "test var"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Var 1
      shell: sh
      run: |
          echo test1
          echo $TVAR1
         
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Print Var 2
      shell: sh
      run: |
          echo test2
          echo $TVAR2

         
